AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "spec/examples.txt"
    - "tmp/**/*"
    - "vendor/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 100

Layout/TrailingEmptyLines:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Max: 40
  Exclude:
    - "spec/**/*_spec.rb"

Style/Documentation:
  Enabled: false

Style/DataInheritance:
  Enabled: false

Style/IfWithBooleanLiteralBranches:
  Enabled: false

Naming/FileName:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
