name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.4

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop
        run: bundle exec rubocop

  spec:
    name: RSpec
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ "3.4", "4.0" ]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: bundle install

      - name: Run RSpec
        run: bundle exec rspec
